### ISSUE TITLE
Support of other Text editors

### ISSUE THREAD

**Issue by edmundmiller** [nextflow-io/language-server#56]
```[tasklist]
### PRs
- [ ] [Helix](https://docs.helix-editor.com/guides/adding_languages.html)
- [ ] https://github.com/mason-org/mason-registry/pull/7480
- [ ] https://github.com/emacs-lsp/lsp-mode/pull/4606
```

**Comment by mehalter** [comment]
I have a branch of `nvim-lspconfig` that adds Nextflow support that works and makes sure there is the one necessary setting set (`nextflow.files.exclude`): https://github.com/mehalter/nvim-lspconfig/commit/873ef31beee09f10554676dcd1dea4c9ed9e7c1e

The contribution guidelines indicate that a language server repo needs to have 100+ stars to be added to avoid bloat of short lived/not very used language servers being added into the codebase. I will keep an eye out and open the PR there when it's appropriate. Here is a minimal code block that can be added to a Neovim configuration to manually add the language server until then:

```lua
-- Hot patch nvim-lspconfig to add Nextflow language server
require("lspconfig.configs").nextflow_ls = {
  default_config = {
    cmd = { "java", "-jar", "nextflow-language-server-all.jar" },
    filetypes = { "nextflow" },
    root_dir = require("lspconfig.util").root_pattern("nextflow.config", ".git"),
    settings = {
      nextflow = {
        files = {
          exclude = { ".git", ".nf-test", "work" },
        },
      },
    },
  },
}

-- Set up the Nextflow language server like any other language server
-- (once the language server is added upstream, this will be the only code necessary)
require("lspconfig").nextflow_ls.setup {
  capabilities = vim.lsp.protocol.make_client_capabilities(),
  -- on_attach = function(client, bufnr) end, -- set up on attach function
}
```

**Comment by mehalter** [comment]
Also worth noting for users that use [AstroNvim](https://astronvim.com/) there is a community [language pack for Nextflow](https://github.com/AstroNvim/astrocommunity/tree/main/lua/astrocommunity/pack/nextflow) that does most of this boiler plate as well as adds syntax highlighting, filetype detection, and icons for the filetype. This can be added easily for those users as well.

The link to the language pack has the instructions for setting it up, but the gist comes down to in your AstroNvim configuration you need to:

1. Add the Nextflow pack to your list of community extensions (the users's `community.lua` file):

```lua
{ import = "astrocommunity.pack.nextflow" }
```

2. Add installation details for where you installed the Nextflow language server `.jar` file (goes into the user's `plugins/` folder such as `plugins/nextflow_ls.lua`):

```lua
return {
  "AstroNvim/astrolsp",
  opts = {
    -- This line enables the setup of the Nextfow language server
    servers = { "nextflow_ls" },
    configs = {
      -- Must set the command with the path to your JAR file
      nextflow_ls = {
        cmd = { "java", "-jar", "<path to language-server-all.jar>" },
      },
    },
  },
}
```

**Comment by mehalter** [comment]
@edmundmiller opened a PR here: https://github.com/neovim/nvim-lspconfig/pull/3423

Fingers crossed! Glad to see this modernization happening!

**Comment by mehalter** [comment]
@edmundmiller the neovim lspconfig PR I opened for merged in! Thanks for linking me the vs code download count! That was a valid metric for vetting the language server :)

**Comment by tesujimath** [comment]
FYI [Helix ](https://helix-editor.com/)is working nicely, see pointers in https://github.com/nextflow-io/language-server/issues/82

If you're not interested in all the Nix stuff, once you have a wrapper script called `nextflow-language-server` on your path, these  additions I made in Helix `languages.toml` should get you started:
```
[[language]]
file-types = ["nf"]
language-servers = ["nextflow-language-server"]
name = "nextflow"
scope = "source.nextflow"

[language-server.nextflow-language-server]
command = "nextflow-language-server"

[language-server.nextflow-language-server.config.nextflow]
debug = true

[language-server.nextflow-language-server.config.nextflow.files]
exclude = [".git", ".nf-test", "work"]
```

This is my starter for ten, surely could be improved.

**Comment by nrminor** [comment]
Thanks for sharing this @tesujimath. Would you have any advice on getting syntax highlighting out of this setup? Previously, to work on Nextflow in helix, I was just using Groovy syntax highlighting:

```toml
[[language]]
name = "groovy"
file-types = ["groovy", "nf", "config"]
indent = { tab-width = 4, unit = "    " }
```

This of course no longer works with the Nextflow LSP, but perhaps there's a way to use the Nextflow LS with Groovy syntax highlighting? Fwiw, using the groovy grammar for nextflow did not enable this for me.

**Comment by tesujimath** [comment]
@nrminor I haven't got syntax highlighting working yet, not had much time to look further at that.  Would love to see a config with that. Glad to hear it's basically working for you.

(I tweaked my config for more known file types, updated above.)

**Comment by blex-max** [comment]
@nrminor @tesujimath (and others who perhaps come across this issue) I've got groovy syntax highlighting working with the language server on helix. Many thanks to @tesujimath for the setup. my `languages.toml` is:
```
[[language]]
file-types = ["nf", "nf.test", {glob = "nextflow.config"}]
language-servers = ["nextflow-language-server"]
name = "nextflow"
grammar = "groovy"
scope = "source.nextflow"
indent = { tab-width = 2, unit = "  " }

[language-server.nextflow-language-server]
command = "nextflow-language-server"

...config settings...
```
and then all I did was `cp -r /path/to/helix/runtime/queries/groovy /path/to/helix/runtime/queries/nextflow`. Done :)

**Comment by seb-hyland** [comment]
Hi! Has anyone here tried using this LSP with Eglot? I have tried to little success, see #101.

**Comment by bguo068** [comment]
Thanks to all the great suggestions above! By following them, I managed to make everything work smoothly.

I did encounter a few hurdles. One crucial step for me was adding the following configuration:

```toml
[language-server.nextflow-language-server.config.nextflow]
files = { exclude = [ ".git", ".nf-test", "work" , "res"]} # any other big folders 
```
I don't completely understand why this configuration matters so much, but I suspect it helps the language server avoid parsing unnecessary files. Here is my complete configuration:

```toml
[[language]]
name = "nextflow"
scope = "source.nextflow"
file-types = ["nf", "nf.test", { glob = "nextflow.config" }]
auto-format = true
comment-tokens = ["//"]
block-comment-tokens = { start = "/*", end = "*/" }
indent = { tab-width = 4, unit = " " } # Adjust as per your preference
language-servers = ["nextflow-language-server"]
# NOTE: syntax highlighting only works after both setting grammar to groovy and copying queryies
grammar = "groovy" 
# change to the parent directory of the runtime folder
# cp -r runtime/queries/groovy runtime/queries/nextflow

[language-server.nextflow-language-server]
command = "java"
args = ["-jar", "/Users/gbinux/Downloads/language-server-all.jar"]

[language-server.nextflow-language-server.config.nextflow]
# debug = true
files = { exclude = [ ".git", ".nf-test", "work" , "res"]}
```

Here is a list of notes that may be helpful for setting up the Nextflow language server for Helix.

1. To enable syntax highlighting, we need to borrow query files from Groovy as suggested by @blex-max. In my case, my runtime folder is located at `~/.config/helix`, so I executed:
```bash
cd ~/.config/helix
cp -r runtime/queries/groovy runtime/queries/nextflow
```

2. Remember to update the Nextflow language server JAR file path to suit your setup. I downloaded the `language-server-all.jar` file from https://github.com/nextflow-io/language-server/releases and moved it to `~/.nextflow`. When specifying the path, avoid using `~`; instead, specify the absolute path.

3. It's important to note that the nextflow language server won't function if you don't have a `.git` folder, as it uses this directory to locate the project root. If you lack a `.git` file, simply run `git init` to generate one. Your `xxx.nf` file does not need to be within the project root.

4. As I highlighted above, it seems that we need to tell the language server folders to exclude, otherwise it won't work, such as adding this your `languages.toml` config file:
```toml
[language-server.nextflow-language-server.config.nextflow]
files = { exclude = [ ".git", ".nf-test", "work" , "res"]} 
```

Here are some screenshots:

<img width="1012" alt="Image" src="https://github.com/user-attachments/assets/a07aac77-5032-49c2-995e-44afbbb77071" />

<img width="1622" alt="Image" src="https://github.com/user-attachments/assets/7f43d104-eb15-4f99-9c90-dbc7d9b60f08" />
